name: vitePress deploy workflow

on:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-and-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build Site
        run: yarn docs:build

      - name: Deploy for Github 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: prod
          folder: docs/.vitepress/dist
          single-commit: true
          clean: true
          github-token: ${{ secrets.GITHUB_TOKEN }}